name: masal
description: "Yeni Masallar Üretin ve Okuyun"

publish_to: 'none' 


version: 1.0.1+9

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.1
  animated_bottom_navigation_bar: ^1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  cloud_firestore: 
  palette_generator: ^0.3.3+6
  shared_preferences: 
  connectivity_plus: ^6.1.3
  device_info_plus: 
  intl:
  liquid_swipe: ^3.1.0
  in_app_purchase:
  url_launcher:
  url_strategy:
  pdf: 
  printing: 

 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/avatar/
 