name: masal
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+6

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.1
  animated_bottom_navigation_bar: ^1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  cloud_firestore: 
  firebase_storage:
  path_provider: ^2.1.2
  palette_generator: ^0.3.3+6
  shared_preferences: 
  connectivity_plus: ^6.1.3
  device_info_plus: 
  intl:
  liquid_swipe: ^3.1.0
  firebase_remote_config:
  in_app_purchase:
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/avatar/
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
