// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs3gZK-_TgEccr7gIcvYU1cVeePH4hzA',
    appId: '1:738778424613:web:f93b73eaa80a94c18e66cc',
    messagingSenderId: '738778424613',
    projectId: 'masal-hikaye',
    authDomain: 'masal-hikaye.firebaseapp.com',
    storageBucket: 'masal-hikaye.firebasestorage.app',
    measurementId: 'G-PBHQW18LSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDNtJU70ID3CQqzBSfuCve97yez44mt9w',
    appId: '1:738778424613:android:e5246f1d8606a5098e66cc',
    messagingSenderId: '738778424613',
    projectId: 'masal-hikaye',
    storageBucket: 'masal-hikaye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNda0htGNF6LifWtseJJ2-Eif1_JgvSjM',
    appId: '1:738778424613:ios:ea893f8451553e788e66cc',
    messagingSenderId: '738778424613',
    projectId: 'masal-hikaye',
    storageBucket: 'masal-hikaye.firebasestorage.app',
    iosBundleId: 'com.temizlikcin.masal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNda0htGNF6LifWtseJJ2-Eif1_JgvSjM',
    appId: '1:738778424613:ios:ea893f8451553e788e66cc',
    messagingSenderId: '738778424613',
    projectId: 'masal-hikaye',
    storageBucket: 'masal-hikaye.firebasestorage.app',
    iosBundleId: 'com.temizlikcin.masal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxs3gZK-_TgEccr7gIcvYU1cVeePH4hzA',
    appId: '1:738778424613:web:a6ad575a4cc510a48e66cc',
    messagingSenderId: '738778424613',
    projectId: 'masal-hikaye',
    authDomain: 'masal-hikaye.firebaseapp.com',
    storageBucket: 'masal-hikaye.firebasestorage.app',
    measurementId: 'G-N6GJVH4YMC',
  );
}
